### ISSUE TITLE
Questions about AMI BIOS keyboard backlight

### ISSUE THREAD

**Issue by fredeason** [Theldus/AMI_BIOS_CodeInjection#1]
Hello, are you familiar with some options in the AMI BIOS? My laptop is the AMI BIOS. I want to set the backlight duration of the computer keyboard. The default is 20 seconds. I want to change it to 10 minutes; but I flip I have searched all the options in the bios, but I can’t find the place where you can set it. I would like to ask you which directory (specific location) this option is in. I searched on the BIOS interface of the computer but couldn’t find it. Then I downloaded it. bin BIOS file, I can’t find the corresponding setting when I open it with AMIBCP, so I would like to ask you where is the specific setting related to the duration of the keyboard backlight.
My BIOS version is:
Version 2.20.1275 Copyright (C) 2021 American Megatrends, Inc.

**Comment by Theldus** [comment]
Hi @fredeason,
Unfortunately this project is focused on older, pre-UEFI BIOSes (something like <2010) and I don't know how newer BIOSes work. However, I believe that this type of setting is not controlled by the BIOS.

Anyway, there are some manufacturers that provide tools to configure certain aspects of the laptop, such as coolers and the keyboard backlight, such as Nitro Sense for Acer Nitro laptops: https://us.v-cdn.net/6029997/uploads/editor/jv/tmohha85bl9t.png

Maybe there is one available for your model too.

**Comment by fredeason** [comment]
Okay, thank you very much, my notebook is relatively small, it seems that this is the only way to change it.

**Comment by fredeason** [comment]
Okay, thank you very much, my notebook is relatively rare, it seems that this is the only way to change it.
